# Generated by Django 4.2.3 on 2023-07-25 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('slugname', models.CharField(default='', max_length=70)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='photos/%m')),
            ],
        ),
        migrations.CreateModel(
            name='StudySource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('description', models.TextField()),
                ('knowledge', models.TextField()),
                ('photo', models.ImageField(upload_to='photos/%m')),
                ('source', models.URLField()),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visiter_type', models.CharField(max_length=70)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('slugname', models.CharField(default='', max_length=70)),
                ('description', models.TextField()),
                ('achieved_goals', models.TextField()),
                ('used_technologies', models.TextField()),
                ('photo', models.ImageField(upload_to='photos/%m')),
                ('global_priory', models.IntegerField()),
                ('group_priory', models.IntegerField()),
                ('source', models.URLField(default='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portfolioApp.category')),
            ],
        ),
    ]
