# Generated by Django 4.2.3 on 2023-07-26 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category of project'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['global_priory'], 'verbose_name': 'Pet project'},
        ),
        migrations.AlterModelOptions(
            name='studysource',
            options={'verbose_name': 'Study source'},
        ),
        migrations.AddField(
            model_name='project',
            name='is_published',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
